#!/bin/bash
width=72
height=42
menu_height=20
backtitle='Disk-menu'
BLK_ID=$(blkid -o device)
BLK_VAL=$(blkid -s UUID -o value);

buid=$(paste <(printf %s "$BLK_ID") <(printf %s "$BLK_VAL") )
# debug
declare -p buid
title='Select a disk'

parts=()
uuids=()
i=1
while read -r type kname uuid; do
	if [[ $type == part ]]; then
		parts[i]=$kname
		uuids[i]=$uuid
		i=$((i + 1))
	fi
done < <(lsblk -rno type,kname,uuid)

pairs=()
for i in "${!parts[@]}"; do
	pairs+=("$i" "${parts[i]} ${uuids[i]}")
done
choice=$(
	dialog \
		--clear \
		--stdout \
		--backtitle "$backtitle" \
		--title "$title" \
		--menu "Select volume (numbers 1-$total): " \
		"$height" "$width" "$menu_height" "${pairs[@]}"
)
declare -p choice
