#!/bin/bash
REQUIRED_PKG="dialog"
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $REQUIRED_PKG|grep "install ok installed")
echo Checking for $REQUIRED_PKG: "$PKG_OK"
if [ "" = "$PKG_OK" ]; then
  echo "No $REQUIRED_PKG. Setting up $REQUIRED_PKG."
  apt install -y $REQUIRED_PKG
fi
json="36.json"
tgdr="/home/wingarmac/.config/cinnamon/spices/calendar@cinnamon.org/"
show_root_menu(){
width=72
height=50
menu_height=10
backtitle="Installer-menu"
title="Setup opions"
menu="Choose one of the following options:"

options=(1 'Add Mint PPA and update' 
         2 'Install Cinnamon '
         3 'Upgrade packages'
         4 'Install and export apt install log'
         5 'Addition software from other repos'
         6 'Upgrade Kernel (+ REBOOT)'
         7 'Resolve Ubuntu Cinnamon issues '
         8 'Install graphic proprietary driver'
	 9 'Personal setting for time format in taskbar'
         x reboot
         q quit )
    
result=$(dialog --clear \
                --backtitle "$backtitle" \
                --title "$title" \
                --menu "$menu" \
                $height $width $menu_height \
                "${options[@]}" \
                2>&1 >/dev/tty)

case "$result" in
    1)  echo 'Mint backport repos installed';
        apt-key adv --recv-keys --keyserver keyserver.ubuntu.com A1715D88E1DF1F24 40976EAF437D05B5 3B4FE6ACC0B21F32 A6616109451BBBF2;
        sh -c 'echo "deb http://packages.linuxmint.com vanessa main upstream import backport romeo" >> /etc/apt/sources.list.d/mint.list';
        sh -c 'echo "deb-src http://packages.linuxmint.com vanessa main upstream import backport romeo" >> /etc/apt/sources.list.d/mint.list';
        apt-key export 451BBBF2 | gpg --dearmour -o /etc/apt/trusted.gpg.d/mint.gpg;
        apt update;
        show_root_menu;;
    2)  echo 'Installation of Cinnamon';
        apt install slick-greeter muffin cinnamon;
        show_root_menu;;
    3)  echo 'Package upgrade';
        apt-get update | dialog --progressbox 30 100;
        sleep 3;
        apt-get upgrade -y  | dialog --progressbox 30 100;
        sleep 3;
        show_root_menu;;
    4)  show_pckg_menu;;
    5)  show_dpkg_menu;;
    6)  bash ubuntu-mainline-kernel -c;
    	bash ubuntu-mainline-kernel -i;
        reboot;;
    7)  show_solver_menu;;
    8)  show_nvidia_menu;;
    9)	cp "$json" "$tgdr" | dialog	--title 'Time format' \
    					--msgbox 'settings applied!' 8 23;
    	show_root_menu;;
    x)  echo Reboot;
        reboot;;
    q)  clear; 
        exit ;;
esac
}
show_cinn_install() {
    local width=72
    local height=22
    local menu_height=10
    local backtitle='Custom Cinnamon desktop environment installer'
    local title='Cinnamon installation'
    local msgbox='Installation complete'

    # Mark unwanted packages as manually installed
    apt-mark manual tillix vim gnome-games pidgin thunderbird libreoffice* firefox ubuntu-session ubuntu-desktop

    # Install Cinnamon desktop environment and other preferred packages
    apt-get update | dialog --progressbox 30 100;
    apt-get --assume-yes install slick-greeter muffin cinnamon numlockx gnome-console gnome-software gimp inkscape eog gnome-text-editor gnome-system-monitor psensor gnome-terminal gedit dbus-x11 gparted gnome-disk-utility | dialog --progressbox 30 100;

    dialog --backtitle "$backtitle" --title "$title" --msgbox "$msgbox" $height $width

    # Set default applications
    xdg-mime default gedit.desktop text/plain
    xdg-mime default gnome-terminal.desktop application/x-shellscript
    xdg-mime default google-chrome.desktop x-scheme-handler/http
    xdg-mime default google-chrome.desktop x-scheme-handler/https    
    
    show_root_menu
}

show_pckg_menu(){
width=72
height=22
menu_height=10
backtitle='Installer-menu'
title='Package options'
menu='Choose one of the following options:'

options=(1 'Custom Cinnamon install'
         2 'Export package list'
         3 'update and upgrade'
         4 'Show root menu'
         x reboot
         q quit )

result=$(dialog --clear \
                --backtitle "$backtitle" \
                --title "$title" \
                --menu "$menu" \
                $height $width $menu_height \
                "${options[@]}" \
                2>&1 >/dev/tty)

case "$result" in
     1) echo 'Custom Cinnamon install';
        show_cinn_install;;
     2) echo 'Manualy installed packages exported';
        sh pkgsexport.sh;;
     3) echo 'Package upgrade';
        apt-get update | dialog --progressbox 30 100;
        sleep 3;
        apt-get upgrade -y  | dialog --progressbox 30 100;
        sleep 3;
        show_pckg_menu;;
     4) show_root_menu;;
     x) echo 'Reboot';
        reboot;;
     q) clear; 
        exit ;;
esac
}
show_dpkg_menu(){
width=72
height=22
menu_height=10
backtitle='Installer-menu'
title='Package options'
menu='Choose one of the following options:'

options=(1 'Install eID (deb)'
         2 'Install Google Chrome (ppa)'
         3 'Install Unified Remote (deb)'
         4 'Install wine-devel (arch 32 added) (ppa)'
         5 'Install Webmin (ppa)'
         6 'Show root menu'
         x reboot
         q quit )

result=$(dialog --clear \
                --backtitle "$backtitle" \
                --title "$title" \
                --menu "$menu" \
                $height $width $menu_height \
                "${options[@]}" \
                2>&1 >/dev/tty)

case "$result" in
     1) echo 'eID installation';
        clear;
	wget https://eid.belgium.be/sites/default/files/software/eid-archive_2022.6_all.deb;
        dpkg -i eid-archive_2022.6_all.deb;
        apt-get update | dialog --progressbox 30 100;
	apt-get install -y eid-mw eid-viewer opensc-pkcs11 libpam-pkcs11 pcscd libpcsclite1 pcscd pcsc-tools | dialog --progressbox 30 100;
	clear;
	service pcscd start;
	systemctl enable pcscd;
	systemctl start pcscd;
        show_dpkg_menu;;
     2) echo 'Google Chrome installation';
     	clear;
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -;
	echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google.list;
	apt-get update | dialog --progressbox 30 100;
	apt-get install google-chrome-stable | dialog --progressbox 30 100;
	apt-get install -f | dialog --progressbox 30 100;
	apt-get update | dialog --progressbox 30 100;
	apt-get upgrade -y | dialog --progressbox 30 100;
	show_dpkg_menu;;
     3) echo 'Unified Remote installation';
        clear;
	wget https://www.unifiedremote.com/download/linux-x64-deb;
        dpkg -i linux-x64-deb | dialog --progressbox 30 100;
	apt-get update | dialog --progressbox 30 100;
        apt-get install -f | dialog --progressbox 30 100;
	show_dpkg_menu;;
     4) echo 'Wine installation';
        clear;
	dpkg --add-architecture i386;
	wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key;
	gpg --no-default-keyring --keyring winehq-archive.gpg --export > tmp.gpg && mv tmp.gpg winehq-archive.gpg
	gpg --no-default-keyring --keyring winehq.gpg --export > tmp.gpg && mv tmp.gpg winehq.gpg
	mv ./wine*.gpg /etc/apt/trusted.gpg.d/
	wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources;
	apt-get update | dialog --progressbox 30 100;
	apt-get install -y --install-recommends winehq-devel | dialog --progressbox 30 100;
	show_dpkg_menu;;
     5) echo 'Webmin installation';
        clear;
	curl -o setup-repos.sh https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh;
	sh setup-repos.sh;
	apt-get update | dialog --progressbox 30 100;
	apt-get install -y apt-transport-https webmin | dialog --progressbox 30 100;
	echo 'done !' | dialog --msgbox 10 20;
	show_dpkg_menu;;
     6) show_root_menu;;
     x) echo 'Reboot';
        reboot;;
     q) clear; 
        exit ;;
esac
}
show_solver_menu(){
width=72
height=22
menu_height=10
backtitle='Installer-menu'
title='Resolver menu'
menu='Choose one of the following options:'

options=(1 'Network applet problem'
         2 'Sound problem (need reboot)'
	 3 'Fix Cinnamon PPA error'
         4 'update and upgrade'
         5 'Show root menu'
         x reboot
         q quit )


result=$(dialog --clear \
                --backtitle "$backtitle" \
                --title "$title" \
                --menu "$menu" \
                $height $width $menu_height \
                "${options[@]}" \
                2>&1 >/dev/tty)

case "$result" in
     1) echo 'Applying changes to network settings';
        clear;
        option_picked "Option 1 Picked";
        touch /etc/network/interfaces;
        echo "auto lo" >> /etc/network/interfaces;
        echo "iface lo inet loopback" >> /etc/network/interfaces;
        cp /etc/netplan/00-installer-config.yaml /etc/netplan/network.yaml;
        rm /etc/netplan/00-installer-config.yaml;
        echo "  renderer: NetworkManager" >> /etc/netplan/network.yaml;
        netplan apply | dialog --progressbox 30 100;
	sleep 3;
        show_solver_menu;;
     2) echo 'Applying changes to sound settings';
        ln -s /usr/share/pipewire /etc/pipewire;
        touch /usr/share/pipewire/media-session.d/with-pulseaudio;
        systemctl --user restart pipewire-session-manager;
        systemctl --user start pulseaudio;
        show_solver_menu;;
     3) cp ./official-package-repositories.pref /etc/apt/preferences.d/;;
     4) echo 'Package upgrade';
        apt-get update | dialog --progressbox 30 100;
        sleep 3;
        apt-get upgrade -y  | dialog --progressbox 30 100;
        sleep 3;
        show_solver_menu;;
     5) show_root_menu;;
     x) echo 'Reboot';
        reboot;;
     q) clear; 
        exit ;;
esac
}
show_nvidia_menu(){
width=72
height=22
menu_height=10
backtitle='Installer-menu'
title='NVidia driver selection'
menu='Choose one of the following options:'

options=(1 'Install nvidia 515'
         2 'Install nvidia 525'
         3 'Update and upgrade'
         4 'Show root menu'
         x reboot
         q quit )

result=$(dialog --clear \
                --backtitle "$backtitle" \
                --title "$title" \
                --menu "$menu" \
                $height $width $menu_height \
                "${options[@]}" \
                2>&1 >/dev/tty)

case "$result" in
     1) echo 'NVidia driver 515 installation';
        apt-get install nvidia-driver-515 -y | dialog --progressbox 30 100;
	sleep 3;
        show_nvidia_menu;;
     2) echo 'NVidia driver 525 installation';
        apt-get install nvidia-driver-525 -y | dialog --progressbox 30 100;
	sleep 3;
        show_nvidia_menu;;
     3) echo 'Package upgrade';
        apt-get update | dialog --progressbox 30 100;
        sleep 3;
        apt-get upgrade -y  | dialog --progressbox 30 100;
        sleep 3;
        show_nvidia_menu;;
     4) show_root_menu;;
     x) echo 'Reboot';
        reboot;;
     q) clear; exit ;;
esac
}

show_root_menu
