#!/bin/bash
show_menu(){
width=72
height=22
menu_height=8
backtitle='Installer-menu'
title='NVidia driver selection'
menu='Choose one of the following options:'

options=(1 'Install nvidia 515'
         2 'Install nvidia 525'
         3 'update and upgrade'
         x reboot
         q quit )

result=$(dialog --clear \
                --backtitle "$backtitle" \
                --title "$title" \
                --menu "$menu" \
                $height $width $menu_height \
                "${options[@]}" \
                2>&1 >/dev/tty)
}
show_menu
case "$result" in
     1) echo 'NVidia driver 515 installation';
     	apt install nvidia-driver-515 -y;
     	show_menu;;
     2) echo 'NVidia driver 525 installation';
     	apt install nvidia-driver-525 -y;
     	show_menu;;
     3) echo 'Package upgrade';
     	apt update && apt upgrade -y;
     	show_menu;;
     x) echo 'Reboot';
     	reboot;;
     q) clear; exit ;;
esac

